### ISSUE TITLE
process hanging because of long stderr

### ISSUE THREAD

**Issue by 0markill** [HenrikBengtsson/future.callr#14] opened 2021-04-04 15:42 UTC
processx hangs when the stderr/output is very long. i use the R CCCP package and it throws a lot of approx solution warnings and there's no way (that i know of) that I can suppress the warnings on the package, this influx of messages causes processx to hang. i managed to get it working by adding stderr = NULL to the r_bg call before the process is launched. it would be great if we could pass parameters to the callr instance.
here's the issue's reference on processx:
https://github.com/r-lib/processx/issues/286

**Comment by HenrikBengtsson** [comment] 2021-04-04 16:31
Before anything else, could you please share a minimal reproducible example that illustrates the slowness when using `plan(future.callr::callr)` that I can have a look at and use for profiling.  One reason I'm asking is that futures use its own way of handling stdout and conditions (message, warning, ...).  It's helpful to distinguish stdout from conditions - they're captured in separate ways.

My hunch says that **processx**'s handling of stdout and stderr should _not_ be involved when using futures, but I might be wrong.

**Comment by 0markill** [comment] 2021-04-04 16:48
Thank you for the quick reply! I'm very new to R lang (started 3 days ago, as i had to debug failing R based servers), unfortunately I cant share the exact snippet, but i'll try to recreate code with similar side effects. The processx issue I attached above was the only hint to what was happening on our end (as that particular function dumped a lot of warnings) and eventually how i managed to come to the conclusion above.

**Comment by HenrikBengtsson** [comment] 2021-04-04 16:56
Got it - no worries.

So, I'd say focus on two different examples.  One that outputs to stdout using for instance `cat()` and `print()` and another that generates warnings using `warning()`.   That second example will most likely also cover what's going on if you'd use `message()`.

I suspect any slowness you're experiencing with **future.callr** is unrelated to **processx**.  Instead, I suspect it can have to do with a huge _number_ of warnings is produced - so it's not the total output length that matters.  You can test this hypothesis, by switching to say, `plan(multisession)` - it might suffer equally much if there's a huge number of warnings produced.  The reason is that warnings are captured one by one and then relayed ("replayed") at the end.

PS. There are workarounds, but lets establish the problem first.

**Comment by 0markill** [comment] 2021-04-05 00:11
Thank you for the hints, much appreciated. I forgot to mention: using `plan(multisession)` worked perfectly fine, which also lead me to believe `future.callr` was the start of the issue. I actually resolved the issue by setting the plan to multisession, till i figure out the main issue.

**Comment by 0markill** [comment] 2021-04-05 02:13
```
library(future)
library(future.callr)
future::plan(future.callr::callr)

options("future.debug" = TRUE)


stderrloop <- function() {
  for (i in 1:1000) {
    write(
      'solve(): system seems singular (rcond: 2.11251e-23); attempting approx solution',
      stderr()
    )
  }
}

catloop <- function() {
  for (i in 1:1000) {
    cat(
      'cat: solve(): system seems singular (rcond: 2.11251e-23); attempting approx solution'
    )
  }
}

warningloop <- function() {
  for (i in 1:1000) {
    warning(
      'warning loop: solve(): system seems singular (rcond: 2.11251e-23); attempting approx solution'
    )
  }
}

f <- future({
  stderrloop()
}, seed = TRUE)
value(f)
```

i tried using cat, print and warning, they all worked fine. the process hangs when using stderr with write

my sessioninfo just in case
```
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] future.callr_0.6.0 future_1.21.0     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6        parallelly_1.24.0 sentryR_1.1.0     magrittr_2.0.1    webutils_1.1      getopt_1.20.3     R6_2.5.0          rlang_0.4.10     
 [9] logger_0.2.0      globals_0.14.0    tools_4.0.3       parallel_4.0.3    xfun_0.22         tinytex_0.31      digest_0.6.27     lifecycle_1.0.0  
[17] optparse_1.6.6    processx_3.5.1    cccp_0.2-7        callr_3.6.0       plumber_1.1.0     later_1.1.0.1     ps_1.6.0          promises_1.2.0.1 
[25] codetools_0.2-16  glue_1.4.2        stringi_1.5.3     swagger_3.33.1    compiler_4.0.3    jsonlite_1.7.2    listenv_0.8.0    
```

**Comment by HenrikBengtsson** [comment] 2021-04-05 17:31
Thanks. That helped. Interesting problem and I don't understand exactly what's going on but it seems to be something (different) on the **callr**/**processx** end.  I've "fixed" this by discarding all stderr output (= passing `callr::r_bg(..., stderr = NULL)`.  This should have little impact on futures, because futures don't capture stderr per se in the first place (because of it's not possible in R https://github.com/HenrikBengtsson/Wishlist-for-R/issues/55).  Note that this is different from capturing messages, warnings, etc. - they are still captured as conditions and relayed.

You can try this out using:

```r
remotes::install_github("HenrikBengtsson/future.callr", ref="develop")
```

Now, it's kind of unusual (=very rare) for R code to output to stderr explicitly.  That requires things such as `cat(..., file = stderr())`.  Code that uses `message()`, `warning()`, and so on don't do that and it's only if such conditions are not captured, R itself will output them to stderr internally.  Do you happen to know which parts of **cccp** output to stderr?

**Comment by 0markill** [comment] 2021-04-06 00:43
Thank you for looking into this! much appreciated. I didnt digtoo deep into the cccp library but i know the specific error is generated from a library called `armadillo c++` which is included in `cccp` as `RcppArmadillo`, which i assume is an R port of the `armadillo c++` library. I think that's the reason why i couldn't suppress the warnings because it doesnt work on R rules?

**Comment by HenrikBengtsson** [comment] 2021-04-06 03:14
> ... i know the specific error is generated from a library called armadillo c++ which is included in cccp as RcppArmadillo, which i assume is a R port of the armadillo c++ library. I think that's the reason why i couldn't suppress the warnings because it doesnt work on R rules?

Yeah, that could be it.  If so, you would not be able to interact with it from R, e.g. it would pass `sink(nullfile(), type = "message")` undected because it's not going via stderr stream of R.  OTH, `R CMD check` looks for calls in native code related to stdout/stderr that's circumventing R's streams and if detected it producing a NOTE (blocking it from being submitted to CRAN) e.g.

```
* checking compiled code ... NOTE
Note: information on .o files is not available
File ‘/path/to/somepkg.Rcheck/somepkg/libs/libsomepkg.so’:
  Found ‘___stderrp’, possibly from ‘stderr’ (C)
  Found ‘___stdoutp’, possibly from ‘stdout’ (C)
  Found ‘_exit’, possibly from ‘exit’ (C)
  Found ‘_printf’, possibly from ‘printf’ (C)
  Found ‘_puts’, possibly from ‘printf’ (C), ‘puts’ (C)
```

which is _not_ the case for **cccp** but maybe there are other ways to output to stderr that is not detect this way.

**Comment by HenrikBengtsson** [comment] 2021-05-03 18:43
Closing. This fix/workaround will be part of the next release of **future.callr**.

**Closed by HenrikBengtsson** 2021-05-03 18:43 UTC
Labels: bug

**Comment by HenrikBengtsson** [comment] 2021-05-04 04:49
FYI, **future.callr** 0.6.1 is now on CRAN
